run:
  command: "node start-server.js"
  
deployment:
  build:
    command: "npm run build"
  run:
    command: "npm start"
    
modules:
  - nodejs-20
  
ports:
  - port: 5000
    visibility: public
    
env:
  NODE_ENV: development