[nix]
channel = "stable-23_11"

[run]
name = "Start application"
command = "node simple-server.js"

[deployment]
run = ["sh", "-c", "npm run build && npm run start"]
ignorePaths = ["node_modules", ".git"]

[env]
NODE_ENV = "development"